image: Visual Studio 2017
environment:
  nodejs_version: "6.9.1"
# Install scripts. (runs after repo cloning)
install:
  - set CI=true
  # Download .NET Core 2.0 SDK and add to PATH
  - ps: $urlCurrent = "https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0/dotnet-sdk-2.0.0-win-x64.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  # Get yarn
  - ps: npm install yarn typescript -g
  - cd %APPVEYOR_BUILD_FOLDER%\src\hosts\CRMCore.WebApp & yarn install
build_script:
  - dotnet --version
  - tsc -v
  - dotnet build
