image: Visual Studio 2017
environment:
  nodejs_version: "6.9.2"
# Install scripts. (runs after repo cloning)
install:
  - set CI=true
  # Download .NET Core 2.0 SDK and add to PATH
  - ps: $urlCurrent = "https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0/dotnet-sdk-2.0.0-win-x64.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  # Get yarn
  - ps: npm install yarn typescript@2.5.3 -g
  - cd %APPVEYOR_BUILD_FOLDER%\src\hosts\CRMCore.WebApp & yarn install
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
build_script:
  - docker images
  - dotnet --version
  - tsc -v
  - ps: |
      cd $env:APPVEYOR_BUILD_FOLDER\src\hosts\CRMCore.WebApp
      dotnet publish -c Release -o ../../../build/release
      cd $env:APPVEYOR_BUILD_FOLDER
      docker build -t crmcore:latest .
      docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
      docker push crmcore/crmcore-dev
test: off
os: Visual Studio 2017
